### ISSUE TITLE
`false_field` replacement suggestion

### ISSUE THREAD

**Issue by niccolomineo** [jacklinke/django-generate-series#11]
Hi, picking up on:

```
Note: As a workaround for an oddity in django’s ORM, we have included a false_field, which always evaluates to False. This allows us to perform a GROUP_BY in the SQL, since the datetime of each Event may be different, but we want to to group them if they fall in the same 7-day period. We would welcome improved approaches.
```

I'd like to suggest:

```
from django.db.models import F, Func

Func(F("field_name"), function="COUNT")
```

**Comment by jacklinke** [comment]
@niccolomineo thank you for your interest!

Can you add a bit more info on this one, though? I'd love to approach this without needing a dedicated field in the model, but I'm still not exactly sure where to apply your suggestion within the subquery.

**Comment by niccolomineo** [comment]
`COUNT`ing through a `Func` object actually bypasses Django's `GROUP BY`. I reckon that's what you were trying to achieve there.

```
event_subquery = (
    Event.objects.filter(ticket_qty__contained_by=OuterRef("term"))
    .order_by()
    .annotate(count_of_tickets=Func("ticket_qty", function="COUNT"))
    .values("count_of_tickets")
)
```

**Comment by jacklinke** [comment]
Thank you @niccolomineo!

Updated in the most recent commit :smile:
