### ISSUE TITLE
Failed to build the docs

### ISSUE THREAD

**Issue by tui95** [jacklinke/django-generate-series#14]
**Describe the bug**
I cannot build the docs

**To Reproduce**
Running the command according to [build the docs](https://django-generate-series.readthedocs.io/en/latest/contributing.html#build-the-docs) section results in failure.
```shell
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v4.3.2

Extension error:
Could not import extension sphinxcontrib.mermaid (exception: cannot import name 'ENOENT' from 'sphinx.util.osutil' (/Users/tui/Library/Caches/pypoetry/virtualenvs/django-generate-series-Vs9BvJIc-py3.9/lib/python3.9/site-packages/sphinx/util/osutil.py))
make: *** [html] Error 2
```

**Expected behavior**
No error should occur and HTML docs should be generated.

**Version:**
 - python: 3.9.0
 - django-generate-series: 0.4.5

**Additional context**
The bug comes from [sphinxcontrib-mermaid](https://github.com/mgaitan/sphinxcontrib-mermaid) version 0.6.x not adapting to [sphinx](https://github.com/sphinx-doc/sphinx) version 4.0.0 API changes.

**Solutions**
1. Workaround according to https://github.com/mgaitan/sphinxcontrib-mermaid/issues/72#issuecomment-835822975
2. Update `sphinxcontrib-mermaid` version to [0.7.0](https://github.com/mgaitan/sphinxcontrib-mermaid/blob/master/CHANGELOG.rst#07-may-31-2021)

**Comment by jacklinke** [comment]
Not sure how I missed this before, but fixed in latest version. Thank you for the report.
