### ISSUE TITLE
API design

### ISSUE THREAD

**Issue by adamchainz** [jacklinke/django-generate-series#7]
Following your call for input on Twitter...

I think the API is a bit unwieldy in a couple respects.

First, usesr have to generate a model class ahead-of-time. It feels to me this could be done on demand, based on requested output class, and cached.

Second, the 'id' name for the steps of the series could potentially be mixed up with concrete model ID's. I'd suggest "series", "step", or anything else.

I think you should be able to wrap this up into a single function the user needs to call:

```python
def generate_series(start, stop, step=None, *, output_field: type[models.Field]):  # default_bounds etc. to be added
    model_class = make_model_class(output_field, default_bounds)
    return model_class.generate_series(start, stop, step)


@lru_cache(maxsize=128)
def make_model_class(field_class):
    return type(
        f"{field_class.__name__}Series",
        (AbstractBaseSeriesModel,),
        {
            'step': field_class(primary_key=True),
            'Meta': type("Meta", object, {"managed": False}),
        }
    )
    

qs = generate_series(1, 100, output_field=BigIntegerField)
```

If a user often needs series of a given field type, with certain args, they can use partial:

```python
from functools import partial

generate_int_series = partial(generate_series, output_field=BigIntegerField)

qs = generate_int_series(1, 100)
```

The package could provide some default `generate_<type>_series` functions for stricter type checking.

**Comment by jacklinke** [comment]
Still working on the background stuff before making all of the major changes recommended here, but so far I changed the model fields to:

- `id`: Standard BigAutoField pk
- `term`: The actual value within the sequence

I did some reading on sequences and series, and `term` seemed like the most appropriate... um... term to use. Also updated the readme and other docs to reflect this.

**Comment by adamchainz** [comment]
why do you have the `id` field? that doesn't exist in the return values. Can you not use `term = model_field(primary_key=True)` ?

**Comment by jacklinke** [comment]
@adamchainz it seemed like a good idea at the time 😬 (famous last words, or something lol)

My thought here was that it might be useful to know _where_ in the sequence a particular value falls. For instance, if we're creating a sequence of days from today to a year from now, it might be useful to know that December 25, 2022 is day 242 in the sequence. Or for sequences where we are stepping, it can be unclear from a glance how far into the sequence a particular value is.

Empirical testing with a few examples seemed to show little overhead, so I added the `id` field in, but maybe it's more overhead than it's worth.

_Would it make sense to make the `id` field an optional field that is not added by default?_

**Comment by jacklinke** [comment]
@adamchainz please take a look at the updated changes if you get a chance, and let me know what you think. Thanks again for all the help!

**Comment by aitoehigie** [comment]
Running Postgres generate_series(-12, 13) will return a series of numbers from the starting figure up to and including the ending figure i.e. -12 to 13

While executing generate_series(-12, 13, output_field=models.IntegerField) will return a series of numbers from the starting figure up to but not including the ending figure.

Was this design decision made to replicate the behavior of Python's range builtin function?

**Comment by jacklinke** [comment]
Closing this. Thanks again for the tips and help @adamchainz. Much appreciated!
